import { Inter} from "next/font/google";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],       // Required: which character sets to load
  weight: ["400", "500", "700"], // Optional: specify which font weights you need
  variable: "--font-inter", // Optional: use as CSS variable
  display: "swap",          // Recommended: font-display strategy
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
